apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: simulator
  labels:
    app: master
spec:
  selector:
    app: master
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8089

---

apiVersion: v1
kind: Service
metadata:
  name: master-internal
  namespace: simulator
  labels:
    app: master
spec:
  selector:
    app: master
  type: ClusterIP
  ports:
  - port: 5557
    targetPort: 5557

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: simulator
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: bucket98/simulator:demo-03
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_HOST
          value: "db-internal.analysis"
        command: ["locust", "-f", "locustfile.py", "--master", "-H", "http://publisher.publisher:8080"]
        ports:
        - containerPort: 8089
        - containerPort: 5557
