apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: simulator
  labels:
    app: worker
spec:
  selector:
    app: worker
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: simulator
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: bucket98/simulator:demo-03
          command: ["locust", "-f", "locustfile.py", "--worker", "--master-host", "master-internal"]
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: "db-internal.analysis"
          - name: WINDOW_SIZE
            value: "2"
          - name: OVERLAP_RATIO
            value: "0.5"

