apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: analysis
  labels:
    app: db
spec:
  selector:
    app: db
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: db-internal
  namespace: analysis
  labels:
    app: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: analysis
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: pub
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: db-init
